Базовая стилизация всех страниц
htmlacademy-htmlcss/2342117-sedona-1 pull request #2
Opened 2023-08-03 16:50 UTC by AleksJavaSkript

---
:mortar_board: [Разметка всех страниц](https://up.htmlacademy.ru/htmlcss-individual/1/user/2342117/tasks/4)

---
:mortar_board: [Графика для всех страниц](https://up.htmlacademy.ru/htmlcss-individual/1/user/2342117/tasks/5)

---
:mortar_board: [Базовая стилизация всех страниц](https://up.htmlacademy.ru/htmlcss-individual/1/user/2342117/tasks/6)

2023-08-04 16:34 UTC, Kartaviy-arteom commented on index.html
> +    </ul>
Это несколько спорный список, мы применяем список для элементов у которых есть общий признак. В принципе можно оставить так

2023-08-04 16:34 UTC, Kartaviy-arteom commented on index.html
>  <body>
`<body>` тут быть его не должно

2023-08-04 16:34 UTC, Kartaviy-arteom commented on index.html
> +      <p id="part1" class="sedona">Седона — небольшой городок в Аризоне,
id тут не нужен и в проекте есть требования к наименования. `part1` не соответствует критериям, но тут его можно просто удалить

2023-08-04 16:34 UTC, Kartaviy-arteom commented on index.html
> +    <section class="advantage">
Этой секции нужен заголовок

2023-08-04 16:34 UTC, Kartaviy-arteom commented on index.html
> +      <ul class="recomendation-list">
форматирование документа, отступы в html визуально показывают вложенность, что упрощает работу с ним

2023-08-08 15:09 UTC, Kartaviy-arteom requested changes

2023-08-08 15:09 UTC, Kartaviy-arteom commented on catalog.html
> +<a class="logo-link" href="index.html">
тут и по двум документам в целом необходимо соблюдать структуру отступов, чтобы можно было быстро понять, как вложены элементы

2023-08-08 15:09 UTC, Kartaviy-arteom commented on catalog.html
> +<main class="catalog-main">
main нигде не закрывается. Ряд элементов также не закрыты, нужно исправить все ошибки валидации

2023-08-08 15:09 UTC, Kartaviy-arteom commented on catalog.html
> +  <form class="sabscribe" action="?" metod="post">
опечатка в слове metod. action берем из демонстрации

2023-08-08 15:09 UTC, Kartaviy-arteom commented on catalog.html
> +    <h2 class="visually-hidden">Гостиницы Седоны.</h2>
этот заголовок лишний

2023-08-08 15:09 UTC, Kartaviy-arteom commented on index.html
> +      <h2 class="visually-hidden">Добро пожаловать в Седону!</h2>
тут он нк нужен и первым по критериям у нас идет заголовок h1 на странице

2023-08-08 15:09 UTC, Kartaviy-arteom commented on index.html
> +        <h3 class="offer-question">Заинтересовались?</h3>
не нужно делать тут два заголовка

2023-08-08 15:09 UTC, Kartaviy-arteom commented on index.html
> +        </div>
можно сделать секцией, у формы заполнить action и исправить нейминг в классах

2023-08-08 15:09 UTC, Kartaviy-arteom commented on index.html
> +<ul class="socials-list">
форматирование

2023-08-08 15:09 UTC, Kartaviy-arteom commented on index.html
> +<h3 class="visually-hidden">Контактный телефон.</h3>
эти заголовки не нужны, можно проще https://up.htmlacademy.ru/htmlcss-individual/1/demos/11131#24

2023-08-08 15:09 UTC, Kartaviy-arteom commented on catalog.html
> +    <img src="#" alt="Горы Седоны.">
img не нужна, это декоративная картинка, сделаем стилями

2023-08-08 15:09 UTC, Kartaviy-arteom commented on catalog.html
> +<button class="button" type="submit">Сбросить</button>
это одна форма и кнопки внутри нее, у сбросить тип reset

2023-08-08 15:09 UTC, Kartaviy-arteom commented on catalog.html
> +<section class="select">
тут лучше сделать большую секцию с результатами выдачи и не выносить сортировку отдельно

2023-08-08 15:09 UTC, Kartaviy-arteom commented on catalog.html
> +      </p></li>
поправить форматирование

2023-08-08 15:09 UTC, Kartaviy-arteom commented on catalog.html
> +<div class="product-card">
этот див не нужен

2023-08-08 15:09 UTC, Kartaviy-arteom commented on catalog.html
> + <button class="pagination-show-more">...</button>
тоже ссылка

2023-08-08 15:09 UTC, Kartaviy-arteom commented on catalog.html
> +</ul>
нужно сгруппировать через name https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox , аналогично радиокнопкам

2023-08-08 15:09 UTC, Kartaviy-arteom commented on index.html
> +<a class="websait-htmlacademy" href="https://htmlacademy.ru/">
тут опечатка в имени класса

2023-08-08 17:36 UTC, AleksJavaSkript commented on catalog.html
> +<main class="catalog-main">
main в смысле? Или что значит главная?

2023-08-08 17:36 UTC, AleksJavaSkript commented on catalog.html
> +<a class="logo-link" href="index.html">
не понял

2023-08-08 17:43 UTC, AleksJavaSkript commented on catalog.html
> +    <h2 class="visually-hidden">Гостиницы Седоны.</h2>
Но он указан на странице. Или убрать visuali hidden?

2023-08-08 17:44 UTC, AleksJavaSkript commented on index.html
> +      <h2 class="visually-hidden">Добро пожаловать в Седону!</h2>
убрал h2

2023-08-08 17:46 UTC, AleksJavaSkript commented on index.html
> +        <h3 class="offer-question">Заинтересовались?</h3>
убрал h2

2023-08-08 17:57 UTC, AleksJavaSkript commented on index.html
> +        </div>
вроде сделал

2023-08-08 17:59 UTC, AleksJavaSkript commented on index.html
> +<ul class="socials-list">
не понимаю

2023-08-08 18:06 UTC, AleksJavaSkript commented on index.html
> +<h3 class="visually-hidden">Контактный телефон.</h3>
исправил. Но по прежнему не пойму как делать, что бы скрин ридер читал мой код. Эти заголовки я делал для скрин ридера

2023-08-08 18:23 UTC, AleksJavaSkript commented on catalog.html
> +<section class="select">
прошу прощения за тупость, не понимаю

2023-08-08 18:25 UTC, AleksJavaSkript commented on catalog.html
> +      </p></li>
что такое форматирование? не пойму что конкретно нужно сделать.
Вот что отвечает гугл:
Форматирование в HTML — это процесс оформления элементов контента посредством HTML-тегов с применением CSS-правил или без него.

2023-08-09 15:46 UTC, AleksJavaSkript commented on catalog.html
> +<main class="catalog-main">
закрыл

2023-08-10 16:14 UTC, Kartaviy-arteom requested changes

2023-08-10 16:14 UTC, Kartaviy-arteom commented on index.html
> +        <h2 class="visually-hidden">Добро пожаловать в Седону!</h2>
тут этот h2 не нужен, и у нас на странице по требованиям критериев должен быть первым h1

2023-08-10 16:14 UTC, Kartaviy-arteom commented on index.html
> +      <section class="advantage">
заголовок для секции

2023-08-10 16:14 UTC, Kartaviy-arteom commented on index.html
> +        <h3 class="offer-question">Заинтересовались?</h3>
а почему h3?

2023-08-10 16:14 UTC, Kartaviy-arteom commented on index.html
> +        <h3 class="sabscribe-heading">Подпишитесь на рассылку</h3>
и тут почему h3 получился?

2023-08-10 16:14 UTC, Kartaviy-arteom commented on index.html
> +        <form class="sabscribe" action="https://echo.htmlacademy.ru/" metod="post">
metod написано с ошибкой

2023-08-10 16:14 UTC, Kartaviy-arteom commented on index.html
> +          <button class="sabscribe-button" type="submit">Подписаться</button>
sabscribe-button написано с ошибкой, это будет нарушение критерия о наименованиях

2023-08-10 16:14 UTC, Kartaviy-arteom commented on index.html
> +        <h3 class="visually-hidden">Соцсети.</h3>
тут в нее входят не только соцсети, а вообще все, и уровень заголовка будет не h3

2023-08-10 16:14 UTC, Kartaviy-arteom commented on catalog.html
> +          <form class="catalog-filter" action="https://echo.htmlacademy.ru/" method="get">
method - тут правилно написано, а в другой форме нет

2023-08-10 16:14 UTC, Kartaviy-arteom commented on catalog.html
> +      <button class="button" type="reset">Сбросить</button>
это все одна форма

2023-08-10 16:14 UTC, Kartaviy-arteom commented on catalog.html
> +
нет блока с количеством гостиниц

2023-08-10 16:14 UTC, Kartaviy-arteom commented on catalog.html
> +
а тут закроется секция резкльтатов поиска

2023-08-10 16:14 UTC, Kartaviy-arteom commented on catalog.html
> +
тут будет секция с результатами поиска

2023-08-10 16:14 UTC, Kartaviy-arteom commented on catalog.html
> +      </div>
тоже секция будет и уровень заголовка думаю изменится

2023-08-10 16:14 UTC, Kartaviy-arteom commented on catalog.html
> +        <a class="websait-htmlacademy" href="https://htmlacademy.ru/">
ошибка в наименовании класса

2023-08-10 18:39 UTC, AleksJavaSkript commented on index.html
> +        <h3 class="visually-hidden">Соцсети.</h3>
исправил на span. Так? Путаюсь с вишуали хиден

2023-08-10 18:47 UTC, AleksJavaSkript commented on index.html
> +      <section class="advantage">
Не понимаю, что требуется. Озаглавить секцию в скрытом формате?
Добавил спан <span class="visually-hidden">Преимущества.</span>

2023-08-10 18:59 UTC, AleksJavaSkript commented on catalog.html
> +      <button class="button" type="reset">Сбросить</button>
сделал, но не уверен

2023-08-10 19:35 UTC, AleksJavaSkript commented on catalog.html
> +
ну так она и не открывалась )

2023-08-14 18:55 UTC, Kartaviy-arteom requested changes

2023-08-14 18:55 UTC, Kartaviy-arteom commented on images/catalog/catalog-Villas.jpg
критерий не соблюден `https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-03`

2023-08-14 18:55 UTC, Kartaviy-arteom commented on images/footer/Logo-footer.svg
строчных букв не должно быть `https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-03`

2023-08-14 18:55 UTC, Kartaviy-arteom commented on images/footer/Phone-number.svg
это текст, а не картинка

2023-08-14 18:55 UTC, Kartaviy-arteom commented on images/footer/Social-telegram.svg
строчных букв не должно быть `https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-03` у всех файлов аналогично

2023-08-14 18:55 UTC, Kartaviy-arteom commented on images/header/logotip.svg
лучше logo, сомневаюсь в этом наименовании

2023-08-14 18:55 UTC, Kartaviy-arteom commented on images/sedona/main-because.svg
эти 3 надписи экспортируй одним файлом

2023-08-14 18:55 UTC, Kartaviy-arteom commented on index.html
> +              height="18" alt="Поиск.>
это декоративная иконка не нужна в разметке

2023-08-14 18:55 UTC, Kartaviy-arteom commented on index.html
> +              <img src="images/header/favorites.svg" width="20"
убрать иконку

2023-08-14 18:55 UTC, Kartaviy-arteom commented on index.html
> +        <img class="greetings-picture" src="images/sedona/main-welcome.svg" width="187.7"
только надпись, остальные картинки убрать нужно

2023-08-14 18:55 UTC, Kartaviy-arteom commented on index.html
> +      <section class="advantage">
да, у секции должен быть заголовок (тег h)

2023-08-14 18:55 UTC, Kartaviy-arteom commented on index.html
> +              <img class="recomendation-picture" src="images/sedona/Advantage-housing.svg" width="75"
у этих карточек убрать картинки

2023-08-14 18:55 UTC, Kartaviy-arteom commented on index.html
> +            <input id="email" name="your-email" type="text" placeholder="your@email.ru">
input добавить атрибут required

2023-08-14 18:55 UTC, Kartaviy-arteom commented on index.html
> +            <img class="footer-picture" src="images/footer/Social-vk.svg" alt="Мы в контакте." width="24"
не нужны картинки у всех соцсетей

2023-08-14 18:55 UTC, Kartaviy-arteom commented on index.html
> +        <img class="footer-picture" src="images/footer/Phone-number.svg" alt="Телефон для связи +78128121212. " width="331"
тут вообще нет картинки

2023-08-14 18:55 UTC, Kartaviy-arteom commented on catalog.html
> +    <header class="page-header">
аналонично главной

2023-08-14 18:55 UTC, Kartaviy-arteom commented on catalog.html
> +
эти 2 img нужно убрать

2023-08-14 18:55 UTC, Kartaviy-arteom commented on catalog.html
> +        <button class="button" type="reset">Сбросить</button>
кнопки внутри формы

2023-08-14 18:55 UTC, Kartaviy-arteom commented on catalog.html
> +        <img src="images/search-bar/list-results.svg"  width="16" height="14" alt="Показать списком.">
это лишнее, удалить эти картинки

2023-08-14 18:55 UTC, Kartaviy-arteom commented on catalog.html
> +              <img class="producе-star" src="images/search-bar/star.svg" alt="#" width="18" height="17">
это тоже удалить

2023-08-14 18:55 UTC, Kartaviy-arteom commented on catalog.html
> +    <footer class="page-footer">
аналогично главной

2023-08-15 09:38 UTC, AleksJavaSkript commented on index.html
> +              height="18" alt="Поиск.>
но она же есть в макете?

2023-08-15 09:39 UTC, AleksJavaSkript commented on index.html
> +              <img src="images/header/favorites.svg" width="20"
убрал, но не понимаю.

2023-08-15 09:46 UTC, AleksJavaSkript commented on index.html
> +              <img class="recomendation-picture" src="images/sedona/Advantage-housing.svg" width="75"
почему? они же есть в макете

2023-08-15 09:48 UTC, AleksJavaSkript commented on index.html
> +            <input id="email" name="your-email" type="text" placeholder="your@email.ru">
сделал, но не уверен что правильно

2023-08-22 17:24 UTC, Kartaviy-arteom requested changes

2023-08-22 17:24 UTC, Kartaviy-arteom commented on styles/styles.css
> +.modal {
эти стили должны быть на ссылке, не на спане. Спан там кстати особо не нужен. Высота не нужна. Не нужно дублировать одни и теже стили.
weight: 160;
  height: 36; - таких значений не бывает. Написание цветов - посмотри критерий `https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01`

2023-08-22 17:24 UTC, Kartaviy-arteom commented on styles/styles.css
> +  background-image: url(../images/sedona/index-background.jpg);
нужно еще задать контрастный фоновый цвет

2023-08-22 17:24 UTC, Kartaviy-arteom commented on styles/styles.css
> +.sedona h2 {
.sedona - плохое название для класса и внутри этого класса нет заголовка

2023-08-22 17:24 UTC, Kartaviy-arteom commented on styles/styles.css
> +}
выравнивание, цвет не тот. размеры шрифта не соответствуют макету

2023-08-22 17:24 UTC, Kartaviy-arteom commented on styles/styles.css
> +}
выравнивание, у всех правил одинаковый отступ. color - он его от body и так отнаследует

2023-08-22 17:24 UTC, Kartaviy-arteom commented on styles/styles.css
> +.invitation-title {
цвет не тот

2023-08-22 17:24 UTC, Kartaviy-arteom commented on index.html
> +            <img class="advantage-picture" src="images/sedona/street-sedona.jpg" width="800" height="383"
объедини заголовок и параграф в div и задай ему синий фон, а заголовку и параграфу белый

2023-08-22 17:24 UTC, Kartaviy-arteom commented on styles/styles.css
> +.recomendation-item-individual {
цвет и фоновый цвет

2023-08-22 19:45 UTC, AleksJavaSkript commented on styles/styles.css
> +}
все изменил, но размер шрифта такой же, как пишут в макете

2023-08-22 22:42 UTC, AleksJavaSkript commented on styles/styles.css
> +}
В комментариях, в новом стилевом пуше оставил варианты решения. Ни один не рабоатет.

2023-08-22 22:47 UTC, AleksJavaSkript commented on styles/styles.css
> +.invitation-title {
Затрудняюсь ответить. 000000 и 333333, как сказал

2023-08-22 22:48 UTC, AleksJavaSkript commented on index.html
> +            <img class="advantage-picture" src="images/sedona/street-sedona.jpg" width="800" height="383"
сделал иначе, если не правильно, переделаю

2023-08-23 10:41 UTC, Kartaviy-arteom commented on index.html
> +            <img class="advantage-picture" src="images/sedona/street-sedona.jpg" width="800" height="383"
из все равно придется оборачивать для выравнивания

2023-08-23 10:49 UTC, Kartaviy-arteom requested changes

2023-08-23 10:49 UTC, Kartaviy-arteom commented on styles/styles.css
> +  font-family: "PT Sans";
семейство не указано

2023-08-23 10:49 UTC, Kartaviy-arteom commented on index.html
> +            <img class="advantage-picture" src="images/sedona/street-sedona.jpg" width="800" height="383"
он не должен быть везде белый

2023-08-27 07:29 UTC, Kartaviy-arteom approved these changes

2023-08-27 07:29 UTC, Kartaviy-arteom commented on images/footer/Phone-number.svg
это нужно удалить

2023-08-27 07:29 UTC, Kartaviy-arteom commented on images/catalog/catalog-Villas.jpg
переименовать в соответствии с критериями (заглавные буквы)

2023-08-27 07:29 UTC, Kartaviy-arteom commented on images/footer/Logo-footer.svg
так же переименовать файл

2023-08-27 07:29 UTC, Kartaviy-arteom commented on styles/styles.css
> +  rgba(131, 179, 211, 0.12);
эту строку удалить

2023-08-27 07:29 UTC, Kartaviy-arteom commented on styles/styles.css
> +  background: url("../images/search-bar/background-image.png") no-repeat lightgray 50% ;
вот тут не понял зачем кнопке этот фон и вот это все

2023-08-27 07:29 UTC, Kartaviy-arteom commented on styles/styles.css
> +  font-family: "PT Sans" sans-serif;
невалидное правило(запятая обязательна)

2023-08-27 07:29 UTC, Kartaviy-arteom commented on styles/styles.css
> +  font-family: "PT Sans" sans-serif;
невалидное правило(запятая обязательна), нужно исправить везде

2023-08-27 07:29 UTC, Kartaviy-arteom commented on styles/styles.css
> +  color: #333333;
ты на body задал color: #333333, чтобы не указывать его всем элементам, в большинстве случаев они его и так наследуют

2023-08-27 07:29 UTC, Kartaviy-arteom commented on styles/styles.css
> +pagination-item-fifth {
в css перед классом ставится точка

2023-08-27 07:29 UTC, Kartaviy-arteom commented on styles/styles.css
> +pagination-link-fifth {
в css перед классом ставится точка

2023-08-27 07:29 UTC, Kartaviy-arteom commented on styles/styles.css
> +  font-family: "PT Sans" sans-serif;
такое нужно исправить везде и шрифт в большинстве случаев отнаследуется от body, можно не указывать его везде

2023-08-27 07:29 UTC, Kartaviy-arteom commented on styles/styles.css
> +  font-family: "PT Sans" sans-serif;
и тут

2023-08-27 07:29 UTC, Kartaviy-arteom commented on styles/styles.css
> +  font-family: PT Sans;
и тут

2023-08-27 07:29 UTC, Kartaviy-arteom commented on index.html
> +    </footer>
тут нужно выполнить [этот критерий](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#ALLY-02)

2023-08-27 07:29 UTC, merged

2023-08-27 10:36 UTC, AleksJavaSkript commented on images/footer/Phone-number.svg
странно, у меня этого давно уже нет. Даже класс называется по другому

2023-08-27 10:39 UTC, AleksJavaSkript commented on styles/styles.css
> +  background: url("../images/search-bar/background-image.png") no-repeat lightgray 50% ;
я не нашел другого решения вопроса

2023-08-27 10:42 UTC, AleksJavaSkript commented on images/catalog/catalog-Villas.jpg
давно переменованы

2023-08-27 10:42 UTC, AleksJavaSkript commented on images/footer/Logo-footer.svg
так же, переименовал давно

2023-08-27 10:43 UTC, AleksJavaSkript commented on styles/styles.css
> +  rgba(131, 179, 211, 0.12);
удалить или добавить background-color: ?

2023-08-27 10:44 UTC, AleksJavaSkript commented on styles/styles.css
> +  font-family: "PT Sans" sans-serif;
Исправил. А есть валидатор для css?

2023-08-27 10:48 UTC, AleksJavaSkript commented on styles/styles.css
> +  font-family: "PT Sans" sans-serif;
ты просто сказал что формы кнопки инпуты и т д шрифт нужно указать, вот я все подряд и сделал