крупные сетки
htmlacademy-htmlcss/2342117-sedona-1 pull request #3
Opened 2023-09-01 16:19 UTC by AleksJavaSkript

2023-09-01 16:53 UTC, Kartaviy-arteom requested changes

2023-09-01 16:53 UTC, Kartaviy-arteom commented on catalog.html
> +          <form class="catalog-filter" action="https://echo.htmlacademy.ru/" method="get">
внутри формы есть теги которые некорректно закрыты/открыты

2023-09-01 16:53 UTC, Kartaviy-arteom commented on catalog.html
> +      </div>
это лишнее

2023-09-01 16:53 UTC, Kartaviy-arteom commented on index.html
> +            <img class="advantage-picture" src="images/sedona/street-sedona.jpg" width="800px" height="390px"
width="800px" height="390px" должно быть width="800" height="390", единицы измерения не нужны

2023-09-01 16:53 UTC, Kartaviy-arteom commented on index.html
> +          <li class="advantage-image">
это исправим на созвоне

2023-09-01 16:53 UTC, Kartaviy-arteom commented on styles/styles.css
> +  width: 1200px;
зачем эта ширина тут? паддинг не нужен

2023-09-01 16:53 UTC, Kartaviy-arteom commented on index.html
>          <span class="visually-hidden">Приглашение посетить Седону.</span>
не нкжен этот спан

2023-09-01 16:53 UTC, Kartaviy-arteom commented on index.html
> +        <div class="invitation-title-description">
на этот div можно вынести общие отступы

2023-09-01 16:53 UTC, Kartaviy-arteom commented on styles/styles.css
> +  min-height: 215;
невалидное значение

2023-09-01 16:53 UTC, Kartaviy-arteom commented on styles/styles.css
> +  margin: 0 auto;
попробуй задать теперь фон как в макете

2023-09-01 16:53 UTC, Kartaviy-arteom commented on catalog.html
> +      <div class="product-card-container">
<ul class="product-card" - это список карточек, а не сама карточка, сетку списка нужно подправить, я покажу как на созвоне

2023-09-01 16:53 UTC, Kartaviy-arteom commented on styles/styles.css
> +.pagination-link-fifth {
ссылка занимать должна весь элемент

2023-09-01 16:53 UTC, Kartaviy-arteom commented on catalog.html
> +        <div class="buttons-wrap">
не сокращаем слова в классах,

2023-09-02 16:36 UTC, AleksJavaSkript commented on index.html
> +        <div class="invitation-title-description">
Там указан только падинг из макета вертикальный.
Хотя в задании нужно только горизонтальные отступы.
Но если ты говоришь нужны отступы, могу предположить что нужно оцентровать.
Сделал margin: 0 auto;

2023-09-02 17:27 UTC, AleksJavaSkript commented on styles/styles.css
> +  margin: 0 auto;
Фон задал. Но не могу разобраться с позиционированием изображения.
И появилась непонятная ситуация с оцентрировкой формы. Задал margin o auto. Но в devtools, это свойство перечеркнуто и не могу понять почему. Не нашел более специфичных значений.

2023-09-02 17:57 UTC, AleksJavaSkript commented on styles/styles.css
> +  margin: 0 auto;
понял. Оцентрировал форму за счет падингов контейнера.
Но! 
ширина формы с кнопкой 690
ширина поля инпута 450
ширина кнопки 230

Убрал падинги у формы, убрал маргины у инпута и кнопки. И все равно не влазит в одну строки формы!

2023-09-06 15:39 UTC, Kartaviy-arteom approved these changes

2023-09-18 17:13 UTC, Kartaviy-arteom requested changes

2023-09-18 17:13 UTC, Kartaviy-arteom commented on .editorconfig
это не нужно было удалять. [подробнее тут](https://www.youtube.com/watch?v=wWbDC1C7JEE)

2023-09-18 17:13 UTC, Kartaviy-arteom commented on index.html
> +            <input class="subscribe-input" class="visually-hidden" required id="email" name="Ваш Email" type="text"
class="subscribe-input" class="visually-hidden", visually-hidden тут не нужен и несколько классов пишутся
так class="class-1 class-2 class-3"

2023-09-18 17:13 UTC, Kartaviy-arteom commented on index.html
>            <span class="visually-hidden">Рекомендации.</span>
div class="recomendation" и спан не нужны

2023-09-18 17:13 UTC, Kartaviy-arteom commented on index.html
> +              </svg>
этого тут быть не должно

2023-09-18 17:13 UTC, Kartaviy-arteom commented on index.html
> +              </svg>
этого тут быть не должно

2023-09-18 17:13 UTC, Kartaviy-arteom commented on index.html
> +        </svg>
этого тут быть не должно

2023-09-18 17:13 UTC, Kartaviy-arteom commented on index.html
> +        <img class="greetings-image" src="images/sedona/welcome.svg" width="460" height="350" alt="Природа Седоны.">
тут alt будет норм написать текст, который картинкой вставлен

2023-09-18 17:13 UTC, Kartaviy-arteom commented on styles/styles.css
> +.page-main-container {
что бы контейнер залез на хедер, можно использовать отрицательное значение для margin-top

2023-09-18 17:13 UTC, Kartaviy-arteom commented on styles/styles.css
> +.about-advantage {
лучше сбросить ему margin, не нужно чтобы они там неявно схлопывались

2023-09-18 17:13 UTC, Kartaviy-arteom commented on styles/styles.css
> +.description {
просто выровняй текст в блоке по центру, не нужно зажимать его по ширине. Текст внутри блоков может меняться

2023-09-18 17:13 UTC, Kartaviy-arteom commented on styles/styles.css
> +.recommendation-title {
position: absolute; не нужен, как и в других похожих карточек. При position: absolute карточки сломаются при переполнении

2023-09-18 17:13 UTC, Kartaviy-arteom commented on styles/styles.css
> +  width: 460px;
просто задай элементу padding

2023-09-18 17:13 UTC, Kartaviy-arteom commented on styles/styles.css
> +.subscribe-container {
фон подправить нужно

2023-09-18 17:13 UTC, Kartaviy-arteom commented on index.html
>        <span class="visually-hidden">Как нас найти.</span>
это лишнее

2023-09-18 17:13 UTC, Kartaviy-arteom commented on styles/styles.css
> +  width: 300px;
эта ширина тебе не нужна

2023-09-18 17:13 UTC, Kartaviy-arteom commented on styles/styles.css
> +  padding: 12px 25px;
зажимать содержимое паддингами так не стоит по горизонтали, потом объясню при созвоне

2023-09-18 23:55 UTC, AleksJavaSkript commented on .editorconfig
сознательно не удалял. В корзине не нашел. что делать?

2023-09-18 23:59 UTC, AleksJavaSkript commented on index.html
> +            <input class="subscribe-input" class="visually-hidden" required id="email" name="Ваш Email" type="text"
мистика)

2023-09-19 00:57 UTC, AleksJavaSkript commented on index.html
> +        </svg>
убрал. Но не получается два изображения прикрепить в css к одному элементу, даже если задаю элементу два класса.
Где-то были тренажеры на эту тему. Но думаю обсудим при созвоне. Время жмет.

2023-09-19 01:03 UTC, AleksJavaSkript commented on index.html
> +        <img class="greetings-image" src="images/sedona/welcome.svg" width="460" height="350" alt="Природа Седоны.">
тк что ли? welcome to the gorgeous sedona because the grand canyon luks

2023-09-19 01:20 UTC, AleksJavaSkript commented on styles/styles.css
> +.page-main-container {
Получилось. Но исчез нижней угол логотипа. 
Попробовал применить order: 1;
Но так понял, что он работает только в рамках родителя. То-есть хэдэра(

2023-09-19 01:25 UTC, AleksJavaSkript commented on styles/styles.css
> +.about-advantage {
не много не понял. Это параграф. У него вроде нет маргин по умолчанию, и я не задавал. 
Но ок, прописал маргин ноль.

2023-09-19 02:06 UTC, AleksJavaSkript commented on styles/styles.css
> +.recommendation-title {
к этому правилу так же относится?

.advantage-title-wide::after {
  position: absolute;
  content: "";
  width: 60px;
  height: 2px;
  top: 49%;
  left: 50%;
  margin-left: -30px;
  background-color: rgba(255, 255, 255, 0.30);
}

2023-09-19 02:06 UTC, AleksJavaSkript commented on styles/styles.css
> +.recommendation-title {
Это черта нарисованная в ссс

2023-09-19 02:25 UTC, AleksJavaSkript commented on styles/styles.css
> +  width: 460px;
))

На кнопке, в этой форме, справа два закругления сделал, как на макете.
Теперь выглядывают белые углы(

2023-09-19 02:45 UTC, AleksJavaSkript commented on index.html
>        <span class="visually-hidden">Как нас найти.</span>
для скрин ридеров все по убирали

2023-09-19 02:52 UTC, AleksJavaSkript commented on styles/styles.css
> +  padding: 12px 25px;
ok

2023-11-13 07:06 UTC, merged